_commit: c542436
_src_path: gh:uuidea/profile-template
description: documentation
name: Common-Energy-System-Model
org: uuidea
schema_base_uri: http://data.globalpst.org/Common-Energy-System-Model/
title: Common Energy System Model
